[Project]
name = "Standard Library"
version = "2026.0.1A"
authors = ["Wylan Shoemaker <iso2t@protonmail.com>"]
description = "The standard library for the Cloth programming language."

[Build]
output = "library"
source = "src"

[Dependencies]
